import matplotlib.pyplot as plt
import numpy as np
abnormal = {'_recallFundsFromVault': 1, 'emergencyCommit': 20, 'farm': 9, 'transfer': 9, '_borrowTokenAndUseFinal': 5,
            'claimRewardsForPools': 1, 'isPartitionStrategy': 1, 'init': 4, 'to call withdraw': 1,
            'withdrawInternal': 1,
            'deposit': 20, 'swapOut': 4, 'submit': 7, 'fees': 1, 'getImplementationHolder': 2, 'latestAnswer': 3,
            'buyJayWithERC721': 5, 'startBridgeTokensViaAnyswap': 10, 'swapIn ': 20, 'getReward': 18,
            'transferHunnyOwner': 3,
            'collectFees': 29, 'exchangeRateStored': 4, 'mint': 1, '__ERC20Burnable_init': 2, 'payBackInFull': 11,
            '_withdraw': 2, '_mintFee': 5, 'setTreasuryAddress': 19, 'withdrawNFT': 19}
normal = {'migrate': 11, 'setActiveVault': 10, 'logBytes6': 2, 'logBool': 1, 'distribute': 8, 'convert': 14,
          'logInt': 1,
          '_withdrawOne': 1, 'functionCall': 43, 'isContract': 234, '_functionCallWithValue': 3,
          '_callOptionalReturn': 180,
          'deposit': 113, 'protectedTokens': 1, 'mul': 941, 'setThreshold': 1, 'prepareMigration': 1, 'forceD': 1,
          'adjustPosition': 1,
          '_withdrawSome': 7, 'weightedApr': 1, 'aprAfterDeposit': 1, '_withdraw': 13, 'safeApprove': 12,
          'safeTransfer': 41,
          'withdrawUnderlying': 1, 'div': 508, 'allowance': 179, 'debtValToShare': 31, '_bankTotalEth': 1, 'sub': 1070,
          'add': 896, 'emergencyWithdraw': 1, 'underlyingBalanceStored': 1, 'withdraw': 170, 'hasAssets': 1, 'apr': 1,
          '_apr': 1, 'workFactor': 1, 'getInterestRate': 45, 'manualAllocation': 1, 'logBytes3': 1, 'logBytes11': 1,
          'logBytes': 1, 'logUint': 1, 'logBytes14': 1, 'log': 1, 'logBytes1': 1, 'setSentinel': 7,
          'burn': 119, 'getRoleMember': 15, 'burnFrom': 37, 'setCeiling': 5, 'stake': 15, 'lowerHasMinted': 1,
          'setTransmutationPeriod': 6, 'transmute': 6,
          'getRoleMemberCount': 6, 'swap': 352, 'checkTicks': 52, 'observe': 18, 'totalSupply': 418,
          'transfer': 332, 'transferFrom': 190, 'initialize': 499, 'transferOwnership': 65, 'getReserves': 324,
          'decimals': 181, '_burn': 119, '_mintFee': 94, '_transfer': 322, 'approve': 380, 'balanceOf': 226,
          'calculateInterestRates': 12, '_getOverallBorrowRate': 10, 'getAddress': 4, 'getPriceOracle': 3, 'admin': 381,
          'getSupplyData': 11, 'principalBalanceOf': 12, 'getUserStableRate': 20, 'getUserLastUpdated': 10,
          'batchBalanceOf': 3, 'borrow': 31, 'sendValue': 19, 'getReserveNormalizedVariableDebt': 3, 'flashLoan': 8,
          'getRevision': 26, 'mintToTreasury': 10, 'transferOnLiquidation': 32, '_updateAssetStateInternal': 6,
          'DISTRIBUTION_END': 2, '_updateUserAssetInternal': 3, 'setDistributionEnd': 2, '_getAssetIndex': 5,
          '_delegate': 444, '_implementation': 8, 'getMarketId': 3, '_approve': 77, 'name': 80, 'encode': 155,
          '_update': 86, 'voteAll': 41, 'unvoteAll': 2, 'vote': 41, 'mint': 270, '_execute': 1, 'unpause': 11,
          'pauseOrUnpause': 1, 'unvote': 2, 'withdrawTokenBySeason': 4, 'withdrawTokensBySeasons': 1,
          'withdrawTokensBySeason': 2, '_claimTokenBySeason': 2, 'claimTokensBySeason': 1, 'claimTokensBySeasons': 1,
          'withdrawTokenBySeasons': 2, 'curveToBDV': 3, 'bdv': 2, 'lusdToBDV': 1, '_deposit': 14,
          'claimAndDepositBeans': 1, 'claimAndWithdrawBeans': 1, 'claimAndWithdrawLP': 1, 'propose': 1,
          '_addReserves': 16, 'executeOperation': 1, 'redeemUnderlying': 18, 'safeRewardTransfer': 13,
          'functionCallWithValue': 155, 'updateRewardPerBlock': 1,
          'functionDelegateCall': 80, 'setNotPublic': 17, 'positionInfo': 43, '_addDebt': 51, 'requestFunds': 35,
          'withdrawAll': 58,
          'massUpdatePools': 156, '__Context_init_unchained': 51, 'pendingAlpaca': 51, 'totalLock': 51,
          'delegateBySig': 85,
          'decreaseAllowance': 89, '_msgSender': 273, '_fallback': 188, 'upgradeToAndCall': 34, 'isAuthorised': 8,
          'setPath': 9,
          'myBalance': 38, 'debtShareToVal': 38, 'stakedWantTokens': 1, 'acceptDebt': 35, 'getWrappedNativeAddr': 35,
          'getCashPrior': 49,
          'doTransferIn': 58, 'getBorrowRate': 30, 'delegateToViewAndReturn': 13, '_setInterestRateModel': 1,
          'delegateToViewImplementation': 46,
          'updateRewardToken': 20, 'setWhitelisted': 15, '_getReward': 14, 'unfrozenStakeTime': 8, 'earn': 3,
          'safeTransferETH': 46,
          'getAmountOut': 191, 'sync': 21, 'pairFor': 109, 'sortTokens': 108, '_swapSupportingFeeOnTransferTokens': 23,
          'safeTransferFrom': 131,
          'buyBack1': 1, 'setTreasury': 1, 'totalBalanceOf': 34, '_harvest': 29, 'set': 47, 'withdraw_fee': 1, 'cap': 2,
          'switchFund': 2,
          'beforeDeposit': 2, '_buyWantAndReinvest': 2, '__ERC20_init': 2, 'addNewCompound': 2, 'setVaultMaster': 1,
          'inCaseTokensGetStuck': 1,
          'harvestStrategy': 1, 'setInvestDisabled': 1, 'safeDecreaseAllowance': 40, '_beforeTokenTransfer': 83,
          'setUnirouter': 2, 'earnExtra': 1,
          'harvest': 53, 'getName': 1, 'setStrategist': 1, 'create': 7, 'negative': 6, 'equals': 3, 'logCall': 3,
          'fetchPrice': 8,
          'getPartialRoundUp': 2, 'zeroWei': 6, 'available': 61, 'callOptionalReturn': 46, 'mod': 17,
          'setEarnLowerlimit': 15,
          'balanceOfeCRV': 13, 'withdrawAllETH': 6, 'delStrategy': 3, '': 11, '_mint': 167, 'parseLiquidateArgs': 2,
          '_updateMarket': 2,
          'getIndex': 5, 'addMarket': 5, 'transferOut': 6, '_runPreprocessing': 6, 'exchange': 12, 'that': 10,
          'getNewParAndDeltaWeiForLiquidation': 6, 'to128': 6, 'getStatus': 13, 'to96': 6, 'getPrice': 20,
          'of the utilization ': 19,
          'lastTimeRewardApplicable': 41, 'rewardPerToken': 62, 'stakeWithPermit': 26, '_moveDelegates': 84,
          'safe32': 54,
          'getDepositAmountForBorrow': 17, 'checkpointPrice': 17, '_updateCheckpoints': 10, 'getLoanParamsList': 17,
          'borrowInterestRate': 17, '_getAllInterest': 40, '_nextBorrowInterestRate2': 9, 'claimRewards': 36,
          'getUserLoans': 17,
          'getBorrowAmountForDeposit': 13, 'decreaseApproval': 7, 'vaultTransfer': 9, 'vaultEtherWithdraw': 8,
          '_payBorrowingFee': 8,
          'divCeil': 9, '_payInterest': 8, 'withdrawCollateral': 8, '_adjustValue': 7, '_burnToken': 16,
          '_getInterestRateAndBorrowAmount': 1,
          '_swapsCall_internal': 1, 'getBorrowAmountByParams': 1, '_finalizeOpen': 1, 'getCurrentMargin': 1,
          'queryRate': 19, '_queryRateCall': 19,
          '_queryRate': 19, 'shouldLiquidate': 19, 'aggregator': 27, 'latestAnswer': 127, 'setDecimals': 19,
          'getBorrowAmount': 1,
          '_getBorrowingFee': 1, '_settleFeeRewardForInterestExpense': 1, 'checkPriceDisagreement': 1, 'queryReturn': 1,
          '_initializeInterest': 1, '_payLendingFee': 1, '_setDelegatedManager': 1, 'addBytes32': 1,
          '_verifyTransfers': 6,
          'mintWithEther': 2, 'addCheckpoint': 1, '_getBlockNumber': 1, 'getValueAt': 1, '_settleInterest': 1,
          '_avgBorrowInterestRate': 1, '_getMarginBorrowAmountAndRate': 1, '_gasUsed': 1, 'stringify': 5,
          'getIsClosing': 5, 'getLiquidationSpreadForPair': 5, 'getPartial': 5, 'burnToEther': 2,
          'positionTokenPrice': 3,
          'normalize': 3, 'mintWithToken': 4, '_triggerPosition': 3, 'getMaxEscrowAmount': 21,
          'marginTradeFromDeposit': 3,
          '_getInterestRateAndAmount2': 3, 'getLeverageList': 23, 'withdrawToken': 27, '_protocolInterestRate': 5,
          '_totalAssetSupply': 7, 'depositCollateralToLoan': 3, 'mulScalarTruncate': 17, 'addUInt': 20, 'mulExp3': 3,
          'truncate': 18, 'mulScalar': 20, 'mulUInt': 20, 'mulScalarTruncateAddUInt': 17, 'mulExp': 1, 'divUInt': 23,
          'getExp': 19, 'subUInt': 18, 'addThenSubUInt': 16, 'divScalar': 3, 'getUtilizationAndAnnualBorrowRate': 3,
          'addExp': 6, 'getUtilizationRate': 3, 'divScalarByExp': 13, 'divScalarByExpTruncate': 14, 'invest': 4,
          'balanceAave': 6, '_balanceDydx': 6, 'balanceCompoundInToken': 22, 'burnOnLiquidation': 22, 'isActive': 4,
          '_getBorrowAmountAndRate': 2, 'getOrdersInfoRespectingBalancesAndAllowances': 2, 'universalTransfer': 7,
          '_handleFees': 2, 'universalTransferFrom': 2, 'externalCall': 2, 'universalBalanceOf': 1, '_swap': 134,
          'returns false is an externally-owned account ': 1, '_getTokens': 1, 'calculateOasisReturn': 1,
          'chaiToDai': 1, 'underlyingAssetAddress': 1, '_getInterestRateAndAmount': 2, '_mintToken': 4,
          'updatePrice': 8, 'claimEther': 2, 'burnToToken': 1, 'supplyFulcrum': 2, 'balanceFulcrumInToken': 2,
          '_balanceCompoundInToken': 2, 'upgradeTo': 15, 'cumulateBalanceInternal': 16, '_withdrawSomeFulcrum': 2,
          'rebalanceStableBorrowRate': 2, 'calculateAvailableCollateralToLiquidate': 2, 'isTransferAllowed': 2,
          'balanceDecreaseAllowed': 3, 'backing transfer': 2, 'repayBorrow': 29, 'delegateToImplementation': 12,
          'delegateTo': 7, '_getLowUtilBaseRate': 1, '_withdrawAave': 10, 'balance': 20, 'balanceDydx': 10,
          'getAaveCore': 10, 'getAave': 10, 'balanceCompound': 10, 'approveToken': 10, 'claimToken': 1,
          'updatePool': 51, '_claimCoverRewards': 1, '_safeTransfer': 21, 'updatePools': 1, 'discountedSwap': 7,
          '_toHex': 7, '_emitSwapped': 5, 'swapExactTokensForETH': 46, 'getAmountsOut': 78,
          'setInterfaceImplementer': 1, '_removeTokenFromPartition': 1, 'totalPartitions': 1,
          '_transferByDefaultPartition': 1, '_removePartitionFromTotalPartitions': 1, 'symbol': 34, 'mintInternal': 6,
          'repayBorrowBehalf': 23, 'redeemInternal': 9, 'getCash': 13, 'getAccountSnapshot': 9, 'flashFee': 13,
          'seizeInternal': 1, 'liquidateBorrowInternal': 1, 'redeemUnderlyingInternal': 4,
          'borrowBalanceStoredInternal': 18, 'exchangeRateStoredInternal': 33, 'exchangeRateCurrent': 37,
          'accrueInterest': 3, 'liquidateBorrow': 21, 'mintFresh': 18, 'getCTokenBalanceInternal': 19,
          'setAccessController': 13, 'proposeFeed': 13, 'getAccessController': 13, 'getRoundFeed': 13,
          '_transferOwnership': 16, 'typeAndVersion': 13, 'description': 94, 'unregisterCollateral': 24,
          '_isOperator': 1, 'initializeAccountCollateralTokens': 15, 'borrowInternal': 4, 'borrowBalanceStored': 19,
          'liquidateBorrowFresh': 15, 'doTransferOut': 54, 'balanceOfUnderlying': 4, 'transferTokens': 47,
          'setManager': 3, 'getCashOnChain': 5, 'redeem': 15, 'registerCollateral': 1, '_admin': 3, '_willFallback': 3,
          'redeemFresh': 5, 'balanceOfPool': 3, 'balanceOfWant': 3, '_moveDelegatesByType': 6,
          '_getDelegationDataByType': 6, '_becomeImplementation': 5, '_resignImplementation': 3,
          'supplyRatePerBlock': 15, '_domainSeparator': 1, 'gulp': 2, 'repayBorrowFresh': 1, '_transferTokens': 7,
          'safe96': 7, 'add96': 7, 'freeFromUpTo': 3, 'computeAddress2': 3, 'sellQuote': 8, 'getBaseInput': 30,
          '_twapUpdate': 12, '_RAboveSellQuoteToken': 34, '_sync': 16, 'sellQuoteToken': 30, '_pause': 37,
          '_setupDecimals': 76, 'getFeeRate': 46, '_SolveQuadraticFunctionForTrade': 15, '_RAboveSellBaseToken': 14,
          '_SolveQuadraticFunctionForTarget': 24, 'mulCeil': 23, 'dodoSwapV1': 12, 'dodoSwapV2TokenToToken': 10,
          'DPPFlashLoanCall': 22, '_GeneralIntegrate': 9, '_RBelowSellBaseToken': 9, 'sellBaseToken': 10,
          'claimTokens': 12, 'lockSetProxy': 12, 'sellBase': 13, '_mintRewards': 3, 'getBalanceForRemoval': 9,
          'tokens': 6, 'getTokens': 6, '_doTransfers': 3, '_getReturn': 3, 'addLiquidity': 99, 'doConvert': 2,
          'dispatchTokenRateUpdateEvents': 2, 'dispatchConversionEvent': 2, 'syncReserveBalances': 2,
          'setReserveBalances': 2, 'encodeReserveBalances': 2, 'encodeReserveBalance': 2, 'calculateFee': 2,
          'fundSupplyAmount': 2, 'crossReserveTargetAmount': 2, 'reserveBalances': 3, 'getReturn': 2,
          'decodeReserveBalance': 2, 'decodeReserveBalances': 2, 'updateRecentAverageRate': 2,
          'calcRecentAverageRate': 2, 'encodeAverageRateInfo': 1, 'roundDiv': 1, 'accurateRatio': 1,
          'normalizedRatio': 1, 'reducedRatio': 1, 'time': 2, 'decodeAverageRateD': 2, 'decodeAverageRateN': 2,
          'decodeAverageRateT': 2, '_validReserve': 2, 'addressOf': 2, '_only': 2, 'acceptTokenOwnership': 2,
          '_protected': 2, 'isV28OrHigher': 2, 'connectorTokens': 1, 'getAmountIn': 36, 'quote': 29, 'getAmountsIn': 8,
          'swapExactTokensForTokens': 37, '_revertWithData': 7, 'transformERC20': 3, '_transformERC20Private': 3,
          'getQuoteSigner': 3, '_executeTransformation': 3, 'getTransformWallet': 3, 'getFunctionImplementation': 3,
          'transform': 6, 'safeDiv': 3, 'getTransformerDeployer': 3, '_fillBridgeOrder': 3, 'trade': 3,
          '_computeTakerTokenFillAmount': 3, 'createTransformWallet': 3, 'swapTokensForExactTokens': 20,
          'externalSwap': 1, 'universalApproveMax': 1, 'mixSwap': 2, 'withdrawBaseTo': 1, 'querySellBaseToken': 1,
          'divFloor': 1, 'getOraclePrice': 1, '_ROneBuyBaseToken': 1, '_RAboveBackToOne': 1, 'bid': 2, 'token0': 2,
          'delegate': 71, 'removeLiquidityETH': 2, 'removeLiquidity': 28, 'sqrt': 94, 'safeTokenTransfer': 23,
          'setNervePerBlock': 23, 'poolLength': 23, 'chargeFees': 23, 'whitelistVault': 23, 'leave': 23, 'enter': 42,
          'setStrategy': 23, 'setConvertStrat': 23, 'claim': 10, 'getMultiplier': 24, '_addLiquidity': 48,
          'setBuybackStrat': 3, 'getA': 2, 'to call withdraw': 2, 'getAPrecise': 2, 'updateUserWithdrawFee': 1,
          'calculateWithdrawOneToken': 1, 'calculateWithdrawOneTokenDY': 1, 'within1': 1, '_difference': 1, 'getYD': 1,
          'getD': 1, '_xp': 1, '_getAPrecise': 1, 'difference': 1, 'calculateTokenAmount': 1, 'depositAll': 11,
          'reflectionFromToken': 12, '_getTValues': 12, '_getRValues': 12, 'init': 7, '_transferToExcluded': 12,
          '_transferBothExcluded': 12, '_reflectFee': 12, 'includeAccount': 7, '_transferStandard': 1,
          'initializeMigrate': 1, 'badd': 12, 'bsub': 12, 'bsubSign': 13, 'getSpotPrice': 1, 'BUY': 5, 'bdiv': 11,
          'bmul': 33, 'calcOutGivenIn': 11, 'bpowi': 12, 'btoi': 13, 'bfloor': 11, 'bpow': 12, 'SELL': 6,
          'redeemPackage': 3, '_issueSharesForAmount': 5, 'getUsersYieldAmount': 1, 'getFee': 1,
          'setMinAmountForSwap': 3, 'getReservesList': 1, 'transferUnderlyingTo': 1, 'handleAction': 1, 'addPool': 1,
          '_updateEmissions': 1, '_updatePool': 1, 'UNDERLYING_ASSET_ADDRESS': 1, 'implementation': 6,
          'variableRateSlope1': 1, '_getLendingPool': 1, 'MAX_NUMBER_RESERVES': 1, 'liquidationCall': 1,
          'getUserConfiguration': 1, 'repay': 11, '_onlyLendingPoolConfigurator': 1, 'validateDeposit': 1,
          'validateSetUseReserveAsCollateral': 1, 'validateWithdraw': 1, 'setReserveInterestRateStrategyAddress': 1,
          'getConfiguration': 1, 'getRewardForDuration': 62, 'earned': 20, 'setDepositContract': 1, 'owner': 64,
          'get_lp_token': 1, 'withdrawLUSD': 1, 'openTrove': 1, 'sendToPool': 1, 'increaseLUSDDebt': 1,
          'setAddresses': 2, '_requireCallerIsBOorTroveMorSP': 1, '_checkRole': 1, 'initializeERC20': 1,
          '_closeTrove': 1, 'getBorrowingFeeWithDecay': 1, 'reInsert': 1, '_insert': 1, 'findInsertPosition': 1,
          '_descendList': 1, 'getPrev': 1, 'getTroveStake': 1, 'updateTroveRewardSnapshots': 1,
          'validInsertPosition': 1, 'contains': 1, 'insert': 1, 'getEntireDebtAndColl': 1, 'removeStake': 1,
          '_requireAmountGreaterThanZero': 1, '_applyPendingRewards': 1, 'getTroveStatus': 1, '_requireTCRoverMCR': 1,
          '_requireTroveisActive': 1, '_getNewTroveAmounts': 1, '_requireICRisAboveMCR': 1, 'claimCollateral': 1,
          'setFund': 1, 'sendToFund': 1, '_requireCallerIsTroveManager': 1, 'withdrawColl': 1, '_calcRedemptionRate': 1,
          'getRedemptionRate': 1, 'getBorrowingRate': 1, 'getBorrowingFee': 1, 'getBorrowingRateWithDecay': 1,
          'getRedemptionFeeWithDecay': 1, '_requireValidLUSDRepayment': 1, 'fetchPriceWithoutUMB': 1,
          '_scalePriceByDigits': 1, 'getAddressByString': 1, 'stringToBytes32': 1, '_fetchUMBPrice': 1, 'getFund': 1,
          'getAllowMinting': 1, '_withdrawLUSD': 1, '_setAdmin': 14, 'subExp': 3, 'totalBorrowsCurrent': 3,
          'mintAllowed': 19, 'claimFortress': 1, 'mul_': 8, 'sub_': 5, 'add_': 3, 'updateFortressSupplyIndex': 1,
          'div_': 2, 'lessThanOrEqualExp': 1, '_setFAIMintRate': 1, 'seizeVerify': 1, 'failOpaque': 1,
          'price1CumulativeLast': 1, 'configDigestFromConfigData': 32, 'transferVerify': 2, 'utilizationRate': 5,
          'addToMarketInternal': 3, '_become': 1, 'borrowAllowed': 25, '_addMarketInternal': 1, 'isForeign': 7,
          'execute': 1, 'votingPeriod': 1, 'executeTransaction': 3, 'liquidateCalculateSeizeTokens': 2, 'getReceipt': 1,
          'queueTransaction': 1, 'quorumVotes': 1, 'getStrikeFee': 3, 'fees': 1, 'shareOf': 15, 'availableBalance': 8,
          'getHegicFee': 9, 'setImpliedVolRate': 9, 'exercise': 7, 'sub96': 5, 'swapTokensForExactETH': 81,
          'calcPoolInGivenSingleOut': 2, 'setController': 32, '_writeCheckpoint': 17, 'setSwapFee': 9,
          'setExitFeeRecipient': 14, 'joinswapPoolAmountOut': 16, 'setMinimumBalance': 14, 'exitPool': 14,
          'bpowApprox': 3, 'deployProxyManyToOne': 2, 'getPremiumPercent': 2, 'getMinimumBalance': 2,
          'approveDeployer': 2, 'getPriceObservationInWindow': 2, 'canUpdatePrice': 2, 'computeTwoWayAveragePrice': 2,
          'canUpdatePrices': 2, 'updatePrices': 6, '_getTwoWayPrice': 2, '_getEthPrice': 2, '_getTokenPrice': 2,
          'configure': 3, '_initializeToken': 9, 'computeProxyAddressManyToOne': 1, 'calcPoolOutGivenSingleIn': 1,
          'reindexTokens': 1, 'reweighTokens': 1, 'computeAverageMarketCap': 1, 'getTokenRecord': 1,
          'computeTwoWayAveragePrices': 1, 'computeAverageEthPrices': 1, 'setImplementationAddressManyToOne': 1,
          'totalSupplyAt': 3, '_updateAccountSnapshot': 3, 'calcSingleInGivenPoolOut': 3, 'OnlyOwnerError': 1,
          'fillRfqOrder': 2, 'fillOrKillRfqOrder': 1, 'transferProtocolFeesForPools': 1,
          'delegatecallMigrateFunction': 1, 'signature `Error': 1, 'batch': 1, '_getRevertMsg': 1,
          'swapExactETHForTokensAndMint': 2, 'setPendingOperator': 1, 'addMinter': 1, 'mul_ScalarTruncateAddUInt': 1,
          'removeFixedPrice': 3, 'repayBorrowInternal': 1, 'getBlockNumber': 14, '_queueOrRevert': 2, '_get': 6,
          'min': 3, 'lessThanExp': 2, 'getActions': 2, 'maxFlashLoan': 1, 'removeFeed': 1, 'changeOwner': 1,
          'buyERC721': 12, 'setPaused': 8, 'canPerform': 5, 'flipSaleStarted': 1, 'supportsInterface': 31,
          'contractURI': 1, '_checkSaleAllowed': 1, '_safeMint': 1, '_baseURI': 7, 'getApproved': 10,
          '_addTokenToOwnerEnumeration': 4, 'tokenURI': 17, '_afterTokenTransfer': 1, '_add': 5, 'at': 5, '_tryGet': 5,
          'baseURI': 4, '_numberBurned': 1, '_exists': 1, 'flipPresaleState': 1, 'withdrawPartial': 2, 'mintDuck': 1,
          'walletOfOwner': 2, 'toString': 1, 'setPreSaleWhitelist': 1, 'setBaseURI': 2, 'setWhitelistPrices': 1,
          'isApprovedForAll': 1, 'tokenByIndex': 2, 'setNotRevealedURI': 1, 'setApprovalForAll': 2, 'getBaseURI': 1,
          'price': 2, 'ownerOf': 10, 'setCost': 1, 'setContractURIHash': 2, 'renounceOwnership': 12,
          'setCustomDescription ': 1, 'addHead': 1, 'setSeeder': 1, 'setPreviewURI': 2,
          'swapAndStartBridgeTokensViaAnyswap': 17, '_startBridge': 28, 'sellToUniswap': 3, 'performSimpleSwap': 4,
          'takeFeeAndTransferTokens': 4, 'ethAddress': 4, 'functionStaticCall': 7, 'transferTokensFromProxy': 4,
          'buyOnUniswapV2ForkWithPermit': 1, 'getReservesByPair': 1, 'safeIncreaseAllowance': 1, 'activateFailover': 1,
          'rescueFunds': 1, 'uniApprove': 1, 'callBytes': 1, 'setWhitelist': 94, 'teamMint': 1, 'setOwner ': 1,
          'getCurrentVotes': 30, 'merlinPerProfitBNB': 64, '__Base_init': 26, '__PausableUpgradeable_init': 33,
          '__WhitelistUpgradeable_init': 68, 'performanceFee': 30, '_transferAsset': 30,
          'setWithdrawalFeeFreePeriod': 60, 'transferMerlinOwner': 30, 'setBuybacker': 30, 'withdrawalFee': 30,
          'amountMerlinToMint': 26, 'setCallerOk': 30, 'setWorkers': 30, 'sharesOf': 33, 'principalOf': 33,
          'setRewardsToken': 30, 'profitOf': 30, 'getMinter': 30, 'routePair': 30, 'setNotFlip': 30,
          '_zapAssetsToMerlin': 30, 'mintGov': 30, 'setStakePermission': 30, 'latestRoundData': 37, 'addPhase': 38,
          'pricesInUSD': 30, 'getReward': 71, 'isWhitelist': 56, '__Ownable_init': 42, 'token1': 28, 'depositedAt': 28,
          'WITHDRAWAL_FEE_FREE_PERIOD': 28, 'swapOut ': 2, '_internalRebalance': 12, 'addLiquidityETH ': 18,
          'swapTokenForExactToken': 27, 'mint ': 45, 'snapshot': 19, 'withdrawWETH': 20, 'addSpecialToken ': 25,
          'setTokenStatus ': 27, 'listNewToken ': 20, 'removeLiquidityETH ': 21, 'directSwapAllowed': 2,
          'swapTokenForExactETH': 13, 'addLiquidityPair ': 3, 'setURI': 7, 'liquidityLastAddedOf': 3, 'burn ': 10,
          '__ERC1155_init': 3, 'removeLiquidity ': 5, '_removeLiquidity ': 5, 'safeTransferERC20Token': 5,
          '_getAvgPrice ': 5, 'totalSupplyOf': 6, 'swapExactTokenForETH': 1, '_getNewPrice ': 2, '_createPool ': 1,
          'mint_approved': 7, 'setAllowed': 6, 'reserveMintCards': 6, 'setTransferLock': 6, '_mintCards': 6,
          'setPreRevealURI': 6, '_mintPayable': 6, 'setWallets': 1, 'setup': 1, 'checkSaleIsActive': 1,
          'setMaxPerSaleMint': 1, 'setSaleDates': 1, '_split': 3, 'querySellQuote': 4, '_setReserve': 4,
          'swapExactBNBForTokensSupportingFeeOnTransferTokens': 1, 'claimSpecialReserveFundBatch': 1,
          'undistributedFees': 1, 'pause': 27, 'updateVesters': 1, 'getOwner': 2, 'vestingNonces': 1,
          'getEquivalentAmount': 20, 'withdrawAndGetReward': 20, 'balanceOfRewardEquivalent': 20, 'CPClaimBidCall': 4,
          'reset': 4, 'lastUpdateTimestamp': 34, 'delegates': 1, 'setOracle': 1, 'setMinter': 2, 'cakePriceInBNB': 1,
          '_apy': 1, 'setHunnyPerProfitBNB': 1, 'MINIMUM_LIQUIDITY': 1, 'hunnyBNBFlipToken': 1, 'flipPriceInUSD': 1,
          'tvl': 2, 'apy': 1, 'tvlStaking': 1, 'tvlInBNB': 2, 'rayMul': 1, 'percentMul': 1, 'rayDiv': 1, 'wadToRay': 1,
          'uniswapV3MintCallback': 32, 'uniswapV3SwapCallback': 17, 'collectProtocolFees': 32, '_balance0': 32,
          'position': 32, 'current': 32, 'collect': 24, '_modifyPosition': 24, '_updatePosition': 24, 'compute': 32,
          'balance1': 17, 'divRoundingUp': 23, 'getLiquidityForAmount0': 23, 'getLiquidityForAmounts': 23,
          'getSqrtRatioAtTick': 23, 'checkDeviation': 23, 'amountsDirection': 23, 'increaseAllowance': 8, 'permit': 8,
          'getPositionTicks': 3, 'positionLiquidity': 3, 'getTickAtSqrtRatio': 3, 'add160': 3,
          'getAmount0ForLiquidity': 3, 'getAmountsForLiquidity': 3, 'amountsForTicks': 3, 'burnExactLiquidity': 3,
          'removeLiquidityWithPermit': 25, 'exchangeRateStored': 33, 'WETH': 7, 'swapETHForExactTokens': 25,
          'swapExactTokensForTokensSupportingFeeOnTransferTokens': 25, 'underlyingBalanceInModel': 25,
          'borrowRatePerBlock': 25, 'seize': 21, 'borrowBalanceCurrent': 2, 'removeLiquidityETHWithPermit': 6,
          'factory': 25, 'isEntered': 38, 'modelAddress': 19, 'craftingSaver': 36, 'addDeposit': 19, 'withdrawable': 38,
          'setVariable': 19, 'pow': 19, 'calculate': 19, 'claimPunk': 38, 'updateGovenance': 19, 'unstaking': 19,
          'addForge': 19, 'initializePunkReward': 19, 'start': 19, 'countByAccount': 19, 'initializeForge': 19,
          'setAdmin': 24, 'issue': 19, 'addRelayer': 21, 'depositETH': 30, 'voteProposal': 5, 'executeProposal': 5,
          'totalRelayers': 5, '_relayerBit': 5, 'changeFeeDivisor': 1, 'changeRebalalncerDivisor': 1, 'unlockFNFT': 12,
          'withdrawFNFT': 4, 'createFNFT': 9, 'mintBatch': 10, 'getBalance': 4, 'setDex': 11, 'mapFNFTToToken': 5,
          'removeFNFT': 5, 'updateBalance': 4, 'setTokenVault': 4, 'depositAdditionalToFNFT': 4, 'setLockManager': 5,
          'getAddressesProvider': 4, 'getRoleAdmin': 4, 'getNextId': 5, 'burnBatch': 11, 'pointFNFTToLock': 5,
          'mintAddressLock': 2, 'mintTimeLock': 1, 'uri': 2, 'hasRole': 4, 'setClaim': 1, 'mintValueLock': 2,
          'depositToken': 1, '_revokeRole': 2, 'getLock': 1, 'cloneFNFTConfig': 4, 'receiveRevestOutput': 3,
          'getAddressRegistry': 12, 'stakeLPTokens': 3, 'stakeBasicTokens': 3, 'config': 3, 'receiveFee': 3,
          'updateBasicShares': 2, 'getRewards': 9, 'claimRewardsForToken': 9, 'manualMapWethBasic': 9,
          'getAllocPoint': 9, 'setLPGlobalMul': 18, 'setStakingContract': 9, 'setAddressRegistry': 3,
          'getDisplayValues': 3, 'getWindow': 3, 'fnftIdToLock': 3, 'updateLPShares': 1, 'liquidateBorrowAllowed': 1,
          '_setPriceOracle': 1, 'enterMarkets': 3, 'getAssetsIn': 1, 'setOracleData': 1,
          'getHypotheticalAccountLiquidityInternal': 1, 'sweepToken': 1, 'distributeSupplierRifi': 1,
          'updateRifiSupplyIndex': 1, 'updateJumpRateModel': 6, 'claimRifi': 1, 'selfPermitAllowed': 2, 'selfPermit': 4,
          'selfPermitAllowedIfNecessary': 2, 'selfPermitIfNecessary': 4, 'deferLiquidityCheck': 2, 'liquidity': 4,
          'computeLiquidityRaw': 2, 'computeUniswapPoolAddress': 2, 'observations': 2, 'encodeAmount': 2,
          'debtAllowance': 2, 'loadAssetCache': 2, 'doExitMarket': 2, 'getEnteredMarketsArray': 2, 'getSubAccount': 2,
          'doEnterMarket': 2, 'loadAssetCacheRO': 2, 'CALLER': 4, 'approveDebt': 2, 'moduleIdToProxy': 2, 'tryMul': 45,
          'tryAdd': 24, 'tryDiv': 13, '__ERC20Burnable_init_unchained': 13, 'totalSupplyExact': 2, 'logAssetStatus': 2,
          'beforeTokenTransfer': 3, '_verifyCallResult': 6, '__ERC20Burnable_init': 5, 'revokeRole': 2,
          'renounceRole': 2, 'lend': 2, 'withdrawTokens': 1, 'computeSwap': 1, '_invariant': 2, '_solveInvariant': 1,
          '_getReserves': 3, 'mulRatioTruncateCeil': 2, 'max': 2, 'proposedGetRoundData': 2, 'getRoundData': 4,
          'addPhaseIds': 2, 'parseIds': 2, '_hasApprovedRelayer': 1, '_onJoinPool': 2, '_onSwapGivenIn': 4,
          'stopAmplificationParameterUpdate': 2, '_onSwapGivenOut': 1, '_isOwnerOnlyAction': 1,
          '_setAmplificationData': 1, '_updateInvariantAfterExit': 1, '_mpMint': 1, '_withdrawTokens': 1,
          '_depositTokens': 1, 'computeMintMulti': 1, '_computeMintOutput': 2, '_inBounds': 1, 'computePrice': 1,
          'computeMint': 1, 'tryMod': 1, '_transferOut': 26, 'take': 26, '_transferETH': 11, '_transferInETH': 1,
          'allPairsLength': 1, 'setFreezer': 1, 'desiredLiquidity': 1, '_transferIn': 15, 'beforeTransfer': 1,
          'afterApprove': 1, 'acceptAdmin': 2, 'payBackInFull': 11, 'getStrategyCount': 11, 'setStrategies': 11,
          'getPendingReward': 11, 'getValuePerShare': 11, 'getLoanCreator': 26, 'getLoanListLength': 15,
          'setPoolInfo': 1, 'transferByBank': 1, 'getLoanMinimumLTV': 1, 'changeRateAndLTV': 1, 'totalFees': 1,
          'excludeFromVip': 1, 'includeInVip': 1, '_setTreasuryData': 1, 'getAllMarkets': 1, '_setComptrollerLens': 1,
          'seizeAllowed': 1, 'getHypotheticalAccountLiquidity': 1, 'redeemAllowedInternal': 1, 'repayBorrowAllowed': 6,
          'ensureNonzeroAddress': 1, 'updateVenusSupplyIndex': 1, 'setSwapTokensAtAmount': 16,
          'swapAndLiquifyStepv1': 1, 'swapTokensForOther': 16, 'swapAndLiquify': 1, 'version': 4, 'bridgeFor': 11,
          'setRebasesPaused': 1, "'f": 1, 'setRewardsDuration': 1, 'notifyRewardAmount': 1, 'finishFarming': 1,
          'lastUpdateTime': 1, 'setupSRads': 1, 'isSRads': 1, 'balanceOfAt': 7, 'getNonce': 9, 'instanceCount': 9,
          'trySub': 8, 'getBalanceDelegated': 2, 'calculateNftID': 1, 'delegatedTransferERC20': 1, 'burnRate': 21,
          'pendingBorrowInterest': 14, '_accrueAccountDebt': 8, 'tokenPrice': 14, 'pendingSupplyInterest': 8,
          'selfBurn': 8, '_accrueAccountSupply': 2, '_accrueAccountInterest': 14, '_validateToken': 8,
          '_checkOracleSupport': 8, 'repayAll': 14, '_borrow': 14, 'borrowBalance': 14, 'liquidateAccount': 14,
          '_accrueInterest': 14, 'withdrawBorrow': 2, 'safeRewardTokenTransfer': 2, 'feeRecipient': 6,
          '_convertTokenValues': 6, 'tokenSupported': 12, '_supplyBalance': 6, 'mintVerify': 27, 'setPendingAdmin': 33,
          'redeemVerify': 27, 'onERC721Received': 16, 'notifyRepayBorrow': 16, 'getCollateralStateSupportPools': 16,
          'getBorrowApy': 16, 'orderLiquidated': 16, 'borrowVerify': 11, 'getBorrowed': 16, 'redeemAllowed': 11,
          'setFeedPriceAddressMap': 11, 'getPendingAmountOfBorrow': 15, 'onERC1155Received': 16, 'transferAllowed': 2,
          'pledge721': 11, 'tokenOfOwnerByIndex': 2, 'repayBorrowVerify': 5, 'lockContract': 12, 'mintTransfer': 6,
          'setRandomizerAddress': 11, '_setTokenURI': 6, 'numberMinted': 6, 'publicSaleMint': 6,
          'setAuctionSaleStartTime': 6, 'getAuctionPrice': 6, 'refundIfOver': 3, 'allowlistMint': 3}
sum = 0
abnsum = 0
nsum = 0
abfunctionfrequencylist1 = []
nfunctionfrequencylist1 = []
abfunctionfrequencylist2 = []
nfunctionfrequencylist2 = []
for x in abnormal.values():
    sum += x
    abnsum += x
for x in normal.values():
    sum += x
    nsum += x
for x in abnormal.values():
    abfunctionfrequencylist1.append(x / abnsum)
    abfunctionfrequencylist2.append(x / sum)
for x in normal.values():
    nfunctionfrequencylist1.append(x / nsum)
    nfunctionfrequencylist2.append(x / sum)
ablist=dict(zip(abfunctionfrequencylist1,abfunctionfrequencylist2))
nlist=dict(zip(nfunctionfrequencylist1,nfunctionfrequencylist2))

plt.style.use('bmh')


def plot_beta_hist(ax, data,label, color):
    ax.hist(np.array(data),
            histtype="stepfilled", bins=50, alpha=0.8, density=True,label=label, color=color)


fig, ax = plt.subplots()
plot_beta_hist(ax,abfunctionfrequencylist1,'Abnormal Functions', 'red')
plot_beta_hist(ax,nfunctionfrequencylist1,'Normal Functions', 'blue')

ax.set_title("'bmh' style sheet")

plt.show()